export const routeName = {
    HOMEPAGE: '/',
    CONTACTUS: '/contact',
    BOOKAPPOINTMENT: '/appointment',
    DOCTORDETAILS: '/details',
    SIGNUP: '/signup',
    REGISTER: '/register',
    REGISTERDOCTOR: '/registerdoctor',
    REGISTERPATIENT: '/registerpatient',
    REGISTERADMIN: '/registeradmin',
    SIGNUPDOCTOR: '/signupdoctor',
    SIGNUPPATIENT: '/signuppatient',
    SIGNUPADMIN: '/signupadmin',
    ADMIN:'/admin',
    DOCTORID:'/doctorId',
    DELETE:'/delete',
    APPROVE:'/approve',
    UPDATE:'/update',
    BOARD:'/board',
  }